name: Sync project_data.csv from OneDrive

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:         # Manual trigger available too

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download project_data.csv from OneDrive
        run: |
          curl -L \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" \
            "https://onedrive.live.com/download?resid=922D0F1C88E8E6DB!4218" -o project_data.csv

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        env:
          GH_CSV_TOKEN: ${{ secrets.GH_CSV_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_CSV_TOKEN}@github.com/${{ github.repository }}.git
          git add project_data.csv
          git commit -m "Auto-update project_data.csv" || echo "No changes to commit"
          git push origin HEAD:main
