name: 🔄 Update project_data.csv from Google Drive

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:       # Allows manual run from Actions tab

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download CSV from Google Drive
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1jBXBQRi9ejjhJNgj3vq-HLLfEaqa-TA6" -o project_data.csv

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push if changed
        env:
          GH_TOKEN: ${{ secrets.GH_CSV_TOKEN }}
        run: |
          git add project_data.csv
          git commit -m "🔄 Auto-update project_data.csv from Google Drive" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
