name: Sync project_data.csv from OneDrive

on:
  schedule:
    - cron: "*/30 * * * *"  # ⏱ Runs every 30 minutes
  workflow_dispatch:       # ▶️ Allows manual runs from the Actions tab

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download project_data.csv
        run: |
          curl -L "https://genuinecable-my.sharepoint.com/:x:/p/701037/EbAUFEUfEdJKkwRcbucVVWMBHe24B_wFn1qivfROdG77uw?e=XNSPj9" -o project_data.csv

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push
        run: |
          git add project_data.csv
          git commit -m "🔄 Auto-update project_data.csv" || echo "No changes to commit"
          git push https://x-access-token:${GH_CSV_TOKEN}@github.com/${{ github.repository }}.git
        env:
          GH_CSV_TOKEN: ${{ secrets.GH_CSV_TOKEN }}
