name: 🔄 Update project_data.csv from Google Drive

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download CSV from Google Drive (with HTML check)
        run: |
          FILE_ID=1ojSU4sCrXsiz8unyc34Q_yGKSB4eXJ7J

          echo "Step 1: Attempt initial download..."
          curl -c cookies.txt -s -L "https://drive.google.com/uc?export=download&id=${FILE_ID}" -o response.html

          if grep -q "confirm=" response.html; then
            echo "Step 2: Confirm token found — extracting and downloading actual file..."
            CONFIRM_CODE=$(grep -o 'confirm=[^&]*' response.html | sed 's/confirm=//')
            curl -Lb cookies.txt -s -L "https://drive.google.com/uc?export=download&confirm=${CONFIRM_CODE}&id=${FILE_ID}" -o project_data.csv
          else
            echo "Step 2: No confirmation needed — saving response as CSV"
            mv response.html project_data.csv
          fi

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push CSV update
        env:
          GH_CSV_TOKEN: ${{ secrets.GH_CSV_TOKEN }}
        run: |
          git add project_data.csv
          git commit -m "🔄 Auto-update project_data.csv from Google Drive" || echo "No changes to commit"
          git push https://x-access-token:${GH_CSV_TOKEN}@github.com/${{ github.repository }}.git
